// Code generated by "stringer -type=ClusterStatus"; DO NOT EDIT.

package clustering

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClusterStatusHealthy-0]
	_ = x[ClusterStatusUnhealthy-1]
}

const _ClusterStatus_name = "ClusterStatusHealthyClusterStatusUnhealthy"

var _ClusterStatus_index = [...]uint8{0, 20, 42}

func (i ClusterStatus) String() string {
	if i < 0 || i >= ClusterStatus(len(_ClusterStatus_index)-1) {
		return "ClusterStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClusterStatus_name[_ClusterStatus_index[i]:_ClusterStatus_index[i+1]]
}
