name: Alfa
port: 7070
peers:
  - address: 127.0.0.1
    port: 7171
  - address: 127.0.0.1
    port: 7272
api:
  enabled: true
  address: 127.0.0.1
  port: 8080
services:
  google:
    monitors:
      - type: dns
        name: "DNS check"
        description: "Make sure DNS resolves"
        options:
          hostname: google.com
      - type: ping
        description: "Ensure that the target is reachable"
        options:
          hostname: google.com
          count: 1
          timeout: 1s
          interval: 1s
      - type: http
        options:
          hostname: google.com
          expectedStatus: 200
          timeout: 1s
